name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Docker
        run: |
          brew install --cask docker virtualbox
          brew install docker-machine
          docker-machine create --driver virtualbox default
          docker-machine restart
          eval "$(docker-machine env default)"
          docker-machine regenerate-certs default
          docker-machine restart
      # - name: Prepare Colima
      #   run: |
      #     brew install colima
      #     colima start
      - name: Install Credential Helper and Compose
        run: |
          brew install docker-compose docker-credential-helper
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/kayxue/actixfuwariserve:latest --no-cache
          docker push ghcr.io/kayxue/actixfuwariserve:latest
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ghcr.io/kayxue/actixfuwariserve:latest

